from turtle import *

# width(3)
# up()
# setpos(200, 100)
# print(position())
# down()
# circle(100, 360, 25)
# up()
# setpos(200, -300)
# print(position())
# down()
# circle(100, 360, 8)
# up()
# setpos(-100, 100)
# down()
# circle(100, 720, 4)
# up()
# setpos(-100, -300)
# down()
# circle(100, 720, 8)

# mode('logo')
# width(3)
# bgcolor('orange')
# def move(heading, move, color):
#     seth(heading)
#     fd(move)
# move(90, 100, color('blue'))
# stamp('5')
# move(0, 100, color('blue'))
# stamp(10)
# move(270, 100, color('blue'))
# stamp(5)
# move(0, 100, color('blue'))
# stamp(8)
# move(90, 100, color('blue'))
# stamp(5)
# tower(0, 0, 0, 180)
# color('blue')
# tower(100, 90, 50, 90)
# color('green')
# tower(100, 90, 50, 0)
# color('red')
# tower(100, 90, 50, 0)
# color('pink')
# tower(0, 0, 0, 0)
# tower(100, 90, 50, 0)
# input('pause')

# for i in[0, 1, 2]

# for (i=0 ; i<5 ; i++)

# dot(100, 'blue')
# ht()
speed(10)
# fd(100)
# fd(50)k
# id1=stamp()
# right(90)
# fd(50)
# id2=stamp()
# right(90)
# fd(50)
# id3=stamp()
# right(90)
# clearstamp(id2)
# color('blue')
# # tup = (255.0, 0.0, 0.0)
# for i in range(200):
#     fd(10+1*i)
#     stamp()
#     right(91)
#     print(pos())
# color('red')
# for i in range(200):
#     fd(10+1*i)
#     stamp()
#     right(91)
# color('yellow')
# for i in range(200):
#     fd(10+1*i)
#     stamp()
#     right(91)
# for i in range(2400):
    # undo()
# clearstamps(10)
# stamp()
# up()
# fd(200)
# down()

home()
# width(2)
pen(fillcolor="black", pencolor="red", pensize=2)
# goto(100, 50)
# degrees sets a new angle mesurements units
# degrees(36)
# radians sets angle mesurements units to radian : "Considérons un secteur angulaire, formé de deux droites concourantes distinctes, et un cercle de rayon r tracé dans un plan contenant ces deux droites, dont le centre est le point d'intersection des droites. Alors, la valeur de l'angle en radians est le rapport entre la longueur L de l'arc de cercle intercepté par les droites et le rayon r."
# radians()
# left(90)
for i in range(8):
    fd(100)
    right(45)
# fd(100)
# print(xcor())
# print(ycor())
# print(heading())
# # Turtle steps to coordinates
# print(distance(0, 0))
# Return the angle between the line from turtle position to position specified by (x,y)
# print(towards(0, 0)) 
input('End')
